### ISSUE TITLE
best practices for git

### ISSUE THREAD

**Issue by kossumov** [leggedrobotics/ros_best_practices#18]
Hi. What are the best practices for organizing git repositories?

Should the src/ folder be a git repository? Or should I make each package a separate repository?

**Comment by marco-tranzatto** [comment]
Hi, 
I suggest you read [this post](https://answers.ros.org/question/257855/git-strategy-for-catkin-and-package-folders/?answer=257873#post-id-257873).

Regards,
Marco.

**Comment by kossumov** [comment]
Thanks,
I think it would be great to add it here. At least a link
