### ISSUE TITLE
Wiki: Lecture notes on Using Third-Party Libraries are not available

### ISSUE THREAD

**Issue by yossioo** [leggedrobotics/ros_best_practices#37]
The section [Using Third-Party Libraries](https://github.com/leggedrobotics/ros_best_practices/wiki#using-third-party-libraries) contains a link to the lecture notes [http://courses.csail.mit.edu/6.141/spring2012/pub/lectures/Lec06-ROS.pdf](http://courses.csail.mit.edu/6.141/spring2012/pub/lectures/Lec06-ROS.pdf) that are currently not available for public access (403: Forbidden).

Maybe someone still has the notes and can publish them to another place? Or reference a different source with the relevant information.

**Comment by tomlankhorst** [comment]
Thank you. I will replace the link with an Internet Archive link now.
